### ISSUE TITLE
Project Initial Setup

### ISSUE THREAD

**Issue by TiciaD** [chingu-voyages/v40-geckos-team-18#25]
**__Task Description__**
Setup project configurations and dependencies

**__Technical Considerations__**
- [x] Install t3 stack - (React, Next.js, TailwindCSS, TanstackQuery, tRPC, Prisma)
- [x] Prettier configuration (Code formatting)
- [x] Install Jest (Testing)
- [x] Add 'dev' branch

**__Additional Considerations__**

**Comment by ialej001** [comment]
create-t3-app comes preconfigured with ReactQuery 3.39, not TanStackQuery 4.0. I left as is as it shouldn't be too much of a problem for our app.

Also created our 'development' branch and updated the protection rule to apply to 'main' and 'development'.
