### ISSUE TITLE
Hero component

### ISSUE THREAD

**Issue by TiciaD** [chingu-voyages/v40-geckos-team-18#59]
**__Task Description__**
Create Hero component for landing page, with buttons routing to appropriate pages
***(**TODO**: Decide with team where "Start Here" routes to)***
Should be responsive on desktop and mobile

![Screenshot 2022-08-18 144256](https://user-images.githubusercontent.com/84279128/185471087-7c50c5ad-5554-4cb7-8245-879054b5df4a.png)

![Screenshot 2022-08-18 144310](https://user-images.githubusercontent.com/84279128/185471048-2768f2f7-45a9-4bef-aa73-00dd27053df0.png)

- [ ] import image and use tailwindcss to manage sizing of it
- [ ] Use TailwindCSS and style guide to style text similar to mockup
- [ ] Import Button component from `flowbite-react` set color to 'success'
- [ ] Use TailwindCSS to manage placement of photo, text and buttons
- [ ] Use TailwindCSS to manage responsiveness of photo, text, and buttons

**__Technical Considerations__**
Try to utilize Flowbite component library when possible:
https://flowbite.com/docs/components/buttons/

**__Additional Considerations__**
[Mockup reference](https://www.figma.com/file/5kGltcw2FvojrkSf9PaMKu/MyCarbonFootprint?node-id=0%3A1)
Keep in mind dark mode variation:
![Screenshot 2022-08-18 144243](https://user-images.githubusercontent.com/84279128/185471218-31a659af-7e2d-41d9-8376-cf029f519213.png)
