### ISSUE TITLE
Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v40-geckos-team-18#9]
From voyage-template created by [jdmedlock](https://github.com/jdmedlock): chingu-voyages/voyage-template#6  

**__Task Description__**
- [x] Using everyone's availability posted to [When2Meet](https://www.when2meet.com/) schedule a Kickoff meeting
- [x] Use the [Kickoff meeting template](https://docs.google.com/document/d/1ozP5lLj_R0kqCWdXEpFDR6sIlP9miXp74DFKZlJyktE/edit?usp=sharing) in the shared document directory we've provided to guide the discussion and to record notes, decisions, and assignments
- [x] Set a time for your next meeting for later in the week

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a

**__Resources__**
[Conduct Kickoff Meeting (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#7bf53dc88d9146fd92673ec72d283b2b)

**Member of Epic:** #16
